apiVersion: apps/v1
kind: Deployment
metadata:
  name: rover-r3
  namespace: swarmbuild
  labels:
    app: swarmbuild
    role: rover
    rover: R3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swarmbuild
      role: rover
      rover: R3
  template:
    metadata:
      labels:
        app: swarmbuild
        role: rover
        rover: R3
    spec:
      containers:
        - name: rover
          image: swarmbuild-agent:dev
          imagePullPolicy: IfNotPresent
          args:
            - --id=R3
            - --x=-10
            - --y=-70
            - --battery=0.90
            - --capabilities=foundation,wall,dome-cap,panel,mast
            - --mode=container
            - --heartbeat-ms=700
            - --op-every-ms=360
          env:
            - name: NATS_URL
              value: nats://nats:4222
